apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: docker-nodejs-demo
          image: peelmicro/docker-nodejs-demo
          ports:
            - name: nodejs-port
              containerPort: 3000
          volumeMounts:
            - mountPath: /myvol
              name: myvolume
      volumes:
        - name: myvolume
          awsElasticBlockStore:
            volumeID: vol-0af16d75075776394
