apiVersion: v1
kind: Pod
metadata:
  name: nodehelloworld.example.com
  labels:
    app: helloworld
spec:
  containers:
    - name: docker-nodejs-demo
      image: peelmicro/docker-nodejs-demo
      ports:
        - name: nodejs-port
          containerPort: 3000
